# Generated by Django 5.2.5 on 2025-09-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
