# Generated by Django 5.2.5 on 2025-09-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_modificacion_1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
